---
- name: Start Backup container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}"
    restart_policy: unless-stopped
    env:
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_DB: "{{ databases }}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BACKUP_DIR: "{{ directory }}"
    volumes:
      # Save the database backups on the media volume since that can be seen as secure.
      - "{{ volume_name }}:/backup_volume"
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: "{{ network }}"
