---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: testinfra
  lint: |
    flake8
